<?php
namespace app\modules\v1\controllers;

use common\models\User;
use Yii;
use app\modules\v1\components\ApiController;
use app\modules\v1\models\APIUser;
use yii\db\Exception;

/**
 * User Controller
 */
class UserController extends ApiController
{
    public $modelClass = 'app\modules\v1\models\APIUser';

    public function actions()
    {
        $actions = parent::actions(); // TODO: Change the autogenerated stub

        // disable the "delete" and "create" actions
        unset($actions['delete'], $actions['create']);

        return $actions;
    }

    public function behaviors()
    {
        $behaviors = parent::behaviors();

        $behaviors['authenticator']['except'] = array_merge($behaviors['authenticator']['except'], ['login', 'logout', 'auth', 'reg']);

        return $behaviors;
    }



    // REG
    public function actionReg()
    {
        $request = \Yii::$app->request;
        $post = $request->post();

//        return $post['username'];

        if (!$post) {
            $this->addError('request', 'no registration data');
            return $this->getErrors();
        }

        if( !$post['username'] ) $this->addError( 'username', 'username is required' );
        if( !$post['email'] ) $this->addError( 'email', 'email is required' );
        if( !$post['password'] ) $this->addError( 'password', 'password is required' );

        if( count($this->errors) ){
            return $this->getErrors();
        }

        // is the name unique
        if( User::findOne(["username" => $post['username']]) ){
            $this->addError('username', 'username is used already');
            return $this->getErrors();
        }

        // is the email unique
        if( User::findOne(["email" => $post['email']]) ){
            $this->addError('email', 'email is used already');
            return $this->getErrors();
        }

        $user = new User();
        $user->username = $post['username'];
        $user->email = $post['email'];
        $user->setPassword( $post['password'] );
        $user->generateAuthKey();
//        $user->password_hash = Yii::$app->getSecurity()->generatePasswordHash($post['password']);

        try{
            $user->save(false);
        }catch(Exception $e){
//            throw new \yii\web\HttpException(405, 'Error saving model');
//            $this->addError('request', 'DataBase error');
//            return $this->getErrors();
            $this->addError( 'db', $e->errorInfo );
            return $this->getErrors();
        }
        return ['success' => true, 'user' => $user ];

    }


    // LOGIN
    public function actionLogin()
    {
        $request = \Yii::$app->request;
        $post = $request->post();

//        return $post['username'];

        if( !$post ) {
            $this->addError( 'request', 'no login data' );
            return $this->getErrors();
        }

        if( !$post['username'] ) $this->addError( 'username', 'username is required' );
//        if( !$post['email'] ) $this->addError( 'email', 'email is required' );
        if( !$post['password'] ) $this->addError( 'password', 'password is required' );

        if( count($this->errors) ){
            return $this->getErrors();
        }

        $identity = User::findOne(['username' => $post['username'] ]);

        if( !$identity ){
            $this->addError( 'request', 'user not found' );
            return $this->getErrors();
        }


//        return [ 'password' => $post['password'], "hash" =>  $identity['password_hash'] ];

        if ( Yii::$app->getSecurity()->validatePassword( $post['password'], $identity['password_hash'] )) {
            Yii::$app->user->login($identity);
            return ['success' => true, 'user' => Yii::$app->user->identity];
        }

        $this->addError( 'request', 'wrong login or password' );
        return $this->getErrors();

    }




    // LOGOUT
    public function actionLogout()
    {

        $identity = Yii::$app->user->identity;

        if( !$identity ){
            $this->addError( 'request', 'user is not logged in' );
            return $this->getErrors();
        }

        Yii::$app->user->logout();
        return ['success' => true ];
    }




    // AUTH
    public function actionAuth()
    {
        $identity = Yii::$app->user->identity;

        if( !$identity ){
            $this->addError( 'request', 'user is not logged in' );
            return $this->getErrors();
        }

        return ['success' => true, 'user' => Yii::$app->user->identity ];
    }


}